---
title: "Understanding Schema Therapy"
description: "A broad overview of schema therapy and why it could be useful, from a lay-person perspective."
date: "2024-05-04"
categories:
  - psychotherapy
  - in summary
draft: yes
---

# Disclaimer

Let me preface this post by saying that **I have not formally studied psychology**. I'm coming at this as someone who's generally interested in psychology (an amateur) and has a research background: which means I'm happy to read pop-sci books, textbooks, and academic journals in equal measure; and which also means I have a higher tolerance for jargon-heavy texts. 

Having said that, I *do* get bored after reading enough technical texts, so here's my attempt at summarising what I've learnt about schema therapy in an accessible (in other words, interesting) manner. I'll also list the resources I found most useful in understanding schema therapy.

If you find any mistakes in this post, please do leave a comment. I'm cognisant that my position as an amateur in this field means I don't know what I don't know.

# Overview of schema therapy

So why bother with schema therapy? 



```
Schema therapy is a form of psychotherapy developed by Dr. Jeffrey Young to treat long-standing, entrenched patterns of thinking, feeling, and behaving known as "schemas." It combines elements of cognitive-behavioral therapy, attachment theory, gestalt therapy, and psychoanalysis. The therapy aims to identify and change these maladaptive schemas, often developed in childhood, through various techniques including cognitive restructuring, experiential exercises, and limited re-parenting
```

# How schemas work

## Maladaptive schemas

For a complete list, I recommend reading (the unfortunately titled) "Reinventing Your Life."

## Schema perpetuation

## Schema healing

# Schema modes (in other words: parts of the self)

## Healthy adult

```
This part of the self represents the rational, balanced, and adaptive aspect of personality. It is responsible for making mature decisions, setting boundaries, and nurturing oneself.
```

## Vulnerable child

```
The vulnerable child represents the emotional aspect of personality, particularly the inner child that experienced unmet needs, trauma, or neglect during childhood. This part of the self holds onto emotional pain, fears, and insecurities from the past.
```

## Adaptive coping modes

Compliance, avoidance, and overcompensation

Coping modes developed to protect the vulnerable child from experiencing further pain and distress.

## Dysfunctional coping modes

Surrender, avoidance, and overcompensation

Coping modes that serve to perpetuate negative patterns of behaviour.

# Changing your schemas

The different levels: cognition (thinking), feeling, and experiencing

- Cognitive restructuring
- Behavioural techniques: behaviours such as practicing assertiveness and setting boundaries
- Limited reparenting
- Chair work
- Experiential techniques (revisiting the past: role-playing, imagery, or visualisation)

# Case examples

# In summary

I think the biggest thing I learnt from schema therapy is recognising that we all have a vulnerable child within us--and different people have different proportions as to the amount of time that they inhabit the vulnerable child vs the healthy adult.

# Additional reading

## General audience (self-help)

The following books are well-written and accessible to people who haven't studied psychology.

- Reinventing Your Life: The breakthrough program to end negative behaviour and feel great again by Jeffrey E. Young and Janet S. Klosko ([goodreads](https://www.goodreads.com/book/show/43866.Reinventing_Your_Life))
- Breaking Negative Thinking Patterns: A schema therapy self-help and support book by Gitta Jacob, Hannie van Genderen and Laura Seebauer ([goodreads](https://www.goodreads.com/book/show/24344283-breaking-negative-thinking-patterns))

## Deep dive


# Appendix: Development of schema therapy
