project:
  type: website
  render:
    - "*.qmd"
    - "*.md"
    
website:
  title: "Curated by Chitra"
  navbar:
    left:
      - href: https://code.chitra-ms.com
        text: Code Collection
      - href: https://recipes.chitra-ms.com
        text: Recipes
      - href: https://curation.chitra-ms.com
        text: Curation
    right:
      - href: about/index.qmd
        text: About
      - icon: github
        href: https://github.com/chitrams/chitrams-website
  favicon: /supporting-files/C-logo.png

freeze: true

format:
  html:
    page-layout: full
    theme: 
      - cosmo
      - styles.scss
    toc: true

editor: visual