project:
  type: website

website:
  title: "Curated by Chitra"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/chitrams
  favicon: /supporting-files/C-logo.png

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto