project:
  type: website

website:
  title: "Curated by Chitra"
  navbar:
    left:
      - code-collection.qmd
      - recipes.qmd
      - curation.qmd
    right:
      - about.qmd
      - icon: github
        href: https://github.com/chitrams/chitrams-website
  favicon: /supporting-files/C-logo.png

format:
  html:
    page-layout: full
    theme: 
      - cosmo
      - styles.scss
    toc: true

editor: visual