project:
  type: website
  render:
    - "*.qmd"
    - "*.md"
    
website:
  title: "Curated by Chitra"
  navbar:
    left:
      - href: code-collection/index.qmd
        text: Code Collection
      - href: recipes/index.qmd
        text: Recipes
      - href: curation/index.qmd
        text: Curation
    right:
      - href: about/index.qmd
        text: About
      - icon: github
        href: https://github.com/chitrams/chitrams-website
  favicon: /supporting-files/C-logo.png
  draft-mode: gone

freeze: true

format:
  html:
    page-layout: full
    theme: 
      - cosmo
      - styles.scss
    toc: true

editor: visual