---
title: "Beef noodle salad"
description: "A fresh and delightful main-course salad."
author: ""
date: "2024-05-02"
# image: ""
# image-alt: ""
categories: [mains, effort/medium, time/medium]
date-modified: "2024-05-02"
---

Serves 4. Adapted from David Tanis' Vietnamese Lemongrass Beef and Noodle Salad on NYT Cooking.

## All ingredients, for reference

It is a lot of ingredients, but most of are things you'd have in the pantry anyway if you do a lot of Asian-style cooking. The preparation is also simple, so don't let the ingredient list intimidate you.

**Dipping sauce**

-   5 tablespoons light brown sugar (4+1)
-   3 tablespoons rice vinegar
-   4 tablespoons lime juice (from two large limes, or use bottled)
-   6 tablespoons fish sauce[^1] (4+2)
-   5 garlic cloves - minced (2+3)
-   3 cm piece of ginger - peeled and minced
-   2 chillies - chopped

[^1]: Use good quality fish sauce. In Australia, I prefer Squid or Red Boat. See [this blog post](https://hot-thai-kitchen.com/fish-sauce-101/) for what makes a good good fish sauce.

**Salad**

-   340 g rice vermicelli noodles
-   1 head lettuce
-   1 medium carrot
-   1 small cucumber
-   1 daikon radish

**Beef stir-fry**

-   500 g beef - sliced thinly (less than 1 cm thick)
-   3 tablespoons lemongrass - tender centres finely chopped[^2]
-   Vegetable oil - for stir-frying

[^2]: I would use canned or lemongrass hearts as the middles can be hard to chop when fresh or frozen.

**Garnish**

-   Bunch coriander
-   Bunch mint leaves
-   4 tablespoons crushed roasted peanuts

## (1) Make the dipping sauce

-   4 tablespoons light brown sugar
-   3 tablespoons rice vinegar
-   4 tablespoons lime juice (from two large limes, or use bottled)
-   4 tablespoons fish sauce[^3]
-   2 garlic cloves - minced
-   3 cm piece of ginger - peeled and minced
-   2 chillies - chopped

[^3]: Use good quality fish sauce. In Australia, I prefer Squid or Red Boat. See [this blog post](https://hot-thai-kitchen.com/fish-sauce-101/) for what makes a good good fish sauce.

## (2) Prep the salad

-   340 g rice vermicelli noodles
-   1 head lettuce - yummy leaves washed and separated
-   1 medium carrot - cut and julienned[^4]
-   1 small cucumber - cut and julienned
-   1 daikon radish - cut and julienned

[^4]: In other words, matchsticks. For instructions, see this Serious Eats [guide](https://www.seriouseats.com/how-to-cut-carrots-7963002#toc-to-cut-matchsticksjulienne).

## (3) Stir-fry the beef

-   500 g beef - sliced thinly (less than 1 cm thick)
-   2 tablespoons fish sauce
-   1 tablespoon light brown sugar
-   3 garlic cloves - minced
-   3 tablespoons lemongrass - tender centres finely chopped[^5]
-   Vegetable oil - for stir-frying

[^5]: I would use canned or lemongrass hearts as the middles can be hard to chop when fresh or frozen.

## (4) All together, now

-   Bunch coriander
-   Bunch mint leaves
-   4 tablespoons crushed roasted peanuts

## Notes

I also like to substitute chicken or pork, cooked in a similar way. I haven't figured out how to substitute with tofu.
