---
title: "Crispy chocolate chip cookies"
draft: true
---

Makes 18 cookies. Adapted from [Jeffrey Morgenthaler's](https://jeffreymorgenthaler.com/chocolate-chip-cookies/) chocolate chip cookies.

115g butter, room temperature 75g light brown sugar 125 g white sugar[^1] 1 large egg 5 ml vanilla extract 175g flour 2g salt 2g baking soda 160g chocolate chips

[^1]: Don't reduce the amount of sugar, or the cookies will turn out a lot less crispy. You already know these aren't good for you.

With a mixer, cream the butter and sugars together. Add the egg and vanilla extract and beat until everything is smooth and incorporated.

In a separate bowl, whisk together the flour, salt, and baking soda until they're all incorporated, too. Then start slowly folding that mixture into the wet ingredients.

Add the chocolate chips and nuts after that dough is done.

I like to wrap them up in plastic wrap and then let the dough rest in the fridge overnight, but you don't have to. Either way, you want to make sure the dough is at room temperature before you pop them in the oven.

I use a one-ounce scoop to measure out twelve perfect little dough balls on a sheet pan.

Bake at 400 degrees Fahrenheit/205 degrees Celsius for ten minutes on the middle rack of your oven.

I like to finish mine with some flaky sea salt.

Makes about 20 cookies total.

## Notes
