---
title: "My favourite Yoga With Adriene videos"
description: "A list for future reference."
date: "2024-04-26"
date-modified: "2024-04-26"
categories: [yoga]
---

A list of my favourite yoga videos from Yoga With Adriene, along with some notes as to why I enjoy them. These are the videos I keep coming back to.

# Workouts

[**Move - Day 27: Strong**](https://youtu.be/8CUzG_ny6sg?si=g2iGnXPtd-wbSTFD) - 9/10 Intensity, 10/10 Enjoyment

A more intense practice that focuses on upper-body strength.

[**Move - Day 16: Anchor**](https://youtu.be/vACdgwUuXII?si=s1edAa6y6726gAaH) - 8/10 Intensity, 8/10 Enjoyment

Includes breathwork, core, side planks, legs, and balance-work.

[**Move - Day 3: Stretch**](https://youtu.be/qj9YLsjdAJg?si=phjkIf_L_Dfmxkrm) - 6/10 Intensity, 8/10 Enjoyment

Works on your legs and lower back, with warrior poses held for quite a while.

[**Move - Day 11: Mobility**](https://youtu.be/6s5MEhUblzQ?si=Uot6byaPs8-fYHjG) - 6/10 Intensity, 8/10 Enjoyment

Excellent leg activation with lots of hydrants. Mainly leg + back work.

[**True - Day 13: Strength and Harmony**](https://youtu.be/cNMCZGBquzI?si=Nr1SqD1KrlENZwXh) - 7/10 Intensity, 8/10 Enjoyment

Good core and whole-body exercises. More on the gentle side.

# Energising

[**20-minute Yoga to Shift Perspective**](https://youtu.be/icfwMWYDeac?si=_Z7iY26r1q0SUQ82)- 7/10 Intensity, 10/10 Enjoyment

Includes side planks and some strength work. Excellent for energising, just enough strength work for a bit of warmth.

[**20-minute Morning Flow**](https://youtu.be/LqXZ628YNj4?si=Otdlmu920X0rY5mb)- 7/10 Intensity, 9/10 Enjoyment

Core work, some difficult poses, overall great energising practice

[**Short Wake-Up Flow**](https://youtu.be/j8bEWn2E9uo?si=6tjYZmhnxu_hWmAm) - 4/10 Intensity, 7/10 Enjoyment

Easy practice, gentle full-body flow with some breathwork.

[**Office Break Yoga**](https://youtu.be/M-8FvC3GD8c?si=DmCgh8EoYjVy-tNJ) - 3/10 Intensity, 6/10 Enjoyment

Pretty good for a break when you've been sitting down for a while.

# Stretches, some situation-specific

[**7-minute Post-Run Yoga**](https://youtu.be/vhLbp8ibmEE?si=iEWYJsUyHI3lpajG) - 2/10 Intensity, 10/10 Enjoyment

Does what it says: excellent quad and calf stretches.

[**13-minute Yoga for Digestion**](https://youtu.be/hbguV_f6XOo?si=zoU6GLrLPdGzEtku) - 1/10 Intensity, 10/10 Enjoyment

Really good for when you overeat and feel way too full of food. Makes your belly feel better somehow.

[**13-minute Airport Yoga**](https://youtu.be/JYLlnvoCvGI?si=Q8LFuOujjNqEUEcz) - 2/10 Intensity, 10/10 Enjoyment

A quick, standing full-body stretch, excellent for when you've been sitting down for a while.

[**5-minute Full-Body Stretch**](https://youtu.be/Kvoq4luIYVc?si=G3g1dfhhRO5ja1_P) - 6/10 Intensity, 8/10 Enjoyment

A good full-body stretch (mat-work) that gets you moving.

# Relaxing

[**12-minute Wind-Down Yoga**](https://youtu.be/BiWDsfZ3zbo?si=VTHD_s5CDnLNuyQX) - 1/10 Intensity, 10/10 Enjoyment

A relaxing practice that I really enjoy before bed.

[**20-minute Gentle, Relaxing, Cozy Flow**](https://youtu.be/jHZPtn15agE?si=oyfGbOSOhiIiX6Z4) - 1/10 Intensity, 10/10 Enjoyment

What it says it is: gentle, relaxing, and cozy.
