---
title: "Chewy chocolate chip cookies"
description: "Otherwise known as Chitra's spreadsheet cookies: my ideal cookie is chewy on the inside and crispy on the outside."
draft: yes
---

Makes 24 cookies. This recipe was my own creation.

100g bread flour[^1]
85g all-purpose flour
½ teaspoon salt
½ teaspoon baking soda

115g butter, at room temperature
25g dark brown sugar
50g light brown sugar
100g castor sugar

1 large egg
1 egg yolk[^2]
1 tsp vanilla extract

160g 75%+ chocolate

[^1]: Feel free to substitute with all-purpose flour; in other words, use 185 g of all-purpose flour in total.
[^2]: Feel free to omit the egg yolk if it's too much of a fuss.

You’ll also need

1 large bowl and 1 medium bowl

An electric mixer

Method

Mix flours, salt, and bicarb soda together to ensure homogeneity. Set aside.

Put butter and sugars in a large mixing bowl. Cream with an electric mixer on medium speed until the mixture is homogenous, light brown in colour, and fluffy looking.

To the butter-sugar mix, add the eggs and vanilla extract. Mix on low speed until just combined.

---

Whisk flours, salt and baking soda together to ensure homogeneity. Set aside
Put butter + sugars in a large mixing bowl. Cream with a mixer on medium speed until mixture is homogenous, light brown in colour, and fluffy-looking
To the butter-sugar mix, add the eggs and vanilla extract. Mix on low speed til just combined
Using a wooden spoon or rubber spatula, add flour mixture to the liquid mix in thirds. Stir until just combined (it’s ok if you see some floury bits bc under-mixing > over-mixing)
Fold in your chocolate chips
Cover dough with cling wrap and leave in fridge between 3-48h (I leave mine overnight—it gets better the longer you leave it!)
When ready to bake, preheat oven to 205°C
If you weigh out ~25g dough you’ll get about 24 cookies from this recipe
Bake for 10 minutes
Leave to cool for ~5m so it has time to firm up then eat! Stores well up to 1 week

## Notes

These cookies are chewy due to the extra protein (bread flour, extra yolk) and added moisture from the brown sugar. You can choose to use all AP flour and/or omit the egg yolk if it’s too much of a fuss and it’ll still be quite chewy.