---
title: "Carrot cake (and frostings)"
description: "An easy take on the classic, with several frostings you could choose from."
author: ""
date: "2024-04-03"
# image: ""
# image-alt: ""
categories: [cakes, effort/medium, time/medium]
date-modified: "2024-04-21"
---

# Carrot Cake

*Adapted from Snacking Cakes by Yossy Arefi*

**Ingredients**

-   95g all-purpose flour
-   65g whole wheat flour[^1]
-   1.5 teaspoons baking powder
-   0.5 teaspoons bicarb soda
-   85g sugar
-   2 large eggs
-   155g neutral oil[^2]
-   2 teaspoons ground cardamom
-   2 teaspoons ground cinnamon
-   1 teaspoon ground nutmeg
-   3/4 teaspoon salt
-   225g peeled and grated carrots[^3]
-   60g chopped pitted dates
-   75g chopped toasted pecans[^4]

[^1]: Preference for safflower oil but canola or rapeseed can also be used.

[^2]: This can be substituted with all-purpose flour or any other whole-grain flour; preference for whole wheat for nuttiness

[^3]: Preference for coarsely grated carrots; finely grated carrots leads to smoother, generic cakey texture

[^4]: Preference for toasted pecans: either grill for 2m or pop them in the oven whilst it's preheating, taking them out when they are golden and fragrant (\~10m). The latter is preferable as less likely to burn.

**Method**

1. Preheat oven to 175°C fan-forced. Butter or coat an 8in/20x20cm baking pan[^5] with non-stick spray. Line pan with a strip of parchment paper that hangs over two of the edges.
2. In a medium-sized bowl, sift all-purpose flour, whole wheat flour, baking powder, and bicarb soda. Whisk or mix until well-distributed.
3. In a separate medium-sized bowl, add sugar and eggs. Whisk or mix the mixture until pale and foamy (1m by hand, ~15s by electric mixer; careful not to overmix). Add oil, cardamom, cinnamon, nutmeg, and salt. Continue whisking/mixing until smooth and emulsified.
4. Add dry ingredients to the liquid mixture. Whisk (or use rubber spatula to mix) until well-combined and smooth. Then use rubber spatula to fold in grated carrots, dates, and pecans.
5. Pour batter into prepared pan. Tap pan gently to release any air bubbles and smooth top of batter.
6. Bake cake in middle rack of oven until puffed and golden and tester/skewer/butter knife inserted into the center comes out clean--30-40 minutes. Set pan on a rack to cool for ~15 minutes then use the parchment paper to lift the cake out of the pan and set it on the rack to cool completely.
7. Store the cake, well-wrapped, at room temperature for up to 3 days. This cake also freezes well.

[^1]: Preference for safflower oil but canola or rapeseed can also be used.
[^2]: This can be substituted with all-purpose flour or any other whole-grain flour; preference for whole wheat for nuttiness
[^3]: Preference for coarsely grated carrots; finely grated carrots leads to smoother, generic cakey texture
[^4]: Preference for toasted pecans: either grill for 2m or pop them in the oven whilst it's preheating, taking them out when they are golden and fragrant (~10m). The latter is preferable as less likely to burn.
[^5]: Other pans: a) cupcake tins: 12-18m; b) 9-in round pan: 30-40m

# Frostings

## Cream cheese and whipped cream frosting

-   125g softened cream cheese (left out at room temperature for \~30m-1h)
-   30g confectioners' sugar
-   150g cream
-   2 teaspoons vanilla extract

Method

1.  Take a cold bowl (I place it in the freezer for 15-30m prior to using) and place cream cheese and sugar in bowl.
2.  Mix with electric mixer until well-combined.
3.  Add vanilla extract to mixture.
4.  Either slowly add cream or mix it into the mixture in two batches. Mix with electric mixer until soft peaks form; careful not to overmix.
5.  Spread onto cake when cake has completely cooled (cake has preferably been chilled in the fridge).

## Lemon glaze

-   1 lemon
-   100g confectioners' sugar
-   1T finely grated carrot

Method

1.  Finely zest lemon into a medium bowl. Juice the lemon, and set aside lemon juice.
2.  Add confectioners sugar and finely grated carrot to bowl with zest along with 4tsp of the lemon juice. Whisk vigorously until smooth.
3.  Add more lemon juice as needed to make a thick but pourable glaze.
4.  Pour glaze over cooled cake and let it set for a few minutes before serving.

## Cream cheese and butter frosting

-   250g cream cheese at room temperature
-   100g unsalted butter at room temperature
-   150g powdered/confectioners' sugar
-   1T vanilla extract

## Cream cheese and coconut frosting

*Dorie Greenspan's*

-   250g cream cheese at room temperature
-   113g (I think I used less) unsalted butter at room temperature
-   450g confectioners' sugar
-   1T fresh lemon juice
-   ½ c shredded coconut, optional
-   Toasted finely chopped nuts and/or toasted coconut, for topping, optional

Method

1.  Beat cream cheese and butter together until smooth and creamy.
2.  Gradually add the confectioners' sugar and continue to beat until the frosting is velvety smooth.
3.  Beat in the lemon juice.
4.  Stir coconut in with rubber spatula.

# Notes
