---
title: "Knäckerbröd"
description: "A Scandinavian rye crispbread which uses your sourdough discards."
categories:
  - effort/easy
  - time/waiting
  - bread
date: "2025-04-26"
---

Adapted from [True North Kitchen](https://true-north-kitchen.com/easy-sourdough-rye-crispbread-knackebrod/) and [Alexandra's Kitchen](https://alexandracooks.com/2022/09/11/easy-sourdough-discard-crackers-5-ingredients/). Makes approx. 8 crispbreads.

**Ingredients**

Here's the ratios of how much you'd need for each ingredient:

-   4 parts sourdough discard
-   1 part unsalted butter at room temperature
-   4 parts rye flour
-   A pinch of sea salt
-   Some flaky sea salt for sprinkling

So if I had 200 g of sourdough discard I'd like to use up, then my ingredient list looks like this:

-   200 g sourdough discard
-   50 g butter
-   200 g rye flour

**You'll also need**

-   A medium to large mixing bowl
-   An airtight container
-   A rolling pin
-   Baking paper
-   Baking tray

**Method**

1.  Combine sourdough discard, butter, and rye flour in your mixing bowl. Mix and knead together until a dough forms. Shape into an oval for easy rolling later; if you are using a larger amount of ingredients (e.g. 200 g sourdough discard), split the dough into a few pieces.
2.  Chill your dough. Place dough in your airtight container and leave in fridge overnight.
3.  When you're ready to bake, preheat your oven to 175ºC fan-forced.
4.  Place some parchment paper on your work surface that will fit the baking tray.
5.  Tear off a chunk of your dough, approximately a 5 cm diameter ball, and roll this out on the parchment paper. Roll out into a circle, rectangle, or amoeba. Sprinkle with additional rye flour if needed to avoid sticking. Make sure you're rolling it out *very* thin. If you're shaping into a circle or amoeba (similar in shape to the traditional knäckerbröd, like Leksands), make a hole in the centre with a cookie cutter or cup so the crispbread can bake evenly. I like to make rectangular strips: start with a rectangle and cut them up into 3-4 cm thick lines (similar in shapes to Cruskits).
6.  Sprinkle with your flaky sea salt. Transfer to your baking tray and bake for 10-15 minutes until the crispbread is crisp and golden-brown. Better over-cooked than under, as a crispy crispbread is better than a soggy one.
7.  Repeat steps 4-6 for the remaining dough, rolling it out whilst your batch is baking in the oven.
8.  Once baked, transfer to a wire rack to cool.

**Notes**

You can store this in an airtight container for up to two weeks before the crispbread loses its crispiness.
